Zkly.Web/Controllers/EnterpriseController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;

using PagedList;

using WebGrease.Css.Extensions;

using Zkly.BLL.Repositories;
using Zkly.BLL.ViewModels;

using Zkly.Common;
using Zkly.Common.Dictionary;
using Zkly.Common.Extension;
using Zkly.Common.Log;
using Zkly.Common.Mvc.Attribute;
using Zkly.DAL.Models;

namespace Zkly.Web.Controllers
{
    [Authorize]
    public class EnterpriseController : BaseController
    {
        #region lasy loading repository
        private readonly IInvestAgreementRepository _investAgreementRepository = new InvestAgreementRepository();
        private InvestRepository _investRepository;
        private LoanRepository _loanRepository;
        private MessageRepository _messageRepository;
        private UploadFileInfoRepository _uploadFileInfoRepository;
        private InvestSecondAuditFileReponsitory _investSecondAuditFileReponsitory;

        public InvestRepository InvestRepository
        {
            get { return _investRepository ?? (_investRepository = new InvestRepository()); }
        }

        public LoanRepository LoanRepository
        {
            get { return _loanRepository ?? (_loanRepository = new LoanRepository()); }
        }

        public MessageRepository MessageRepository
        {
            get { return _messageRepository ?? (_messageRepository = new MessageRepository()); }
        }

        public UploadFileInfoRepository UploadFileInfoRepository
        {
            get { return _uploadFileInfoRepository ?? (_uploadFileInfoRepository = new UploadFileInfoRepository()); }
        }

        public InvestSecondAuditFileReponsitory InvestSecondAuditFileReponsitory
        {
            get
            {
                return _investSecondAuditFileReponsitory
                       ?? (_investSecondAuditFileReponsitory = new InvestSecondAuditFileReponsitory());
            }
        }

        #endregion

        #region 个人主页

        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();

            var model = new EnterpriseViewModel
            {
                Loans = LoanRepository.GetLoansByUserId(userId),
                Invests = InvestRepository.GetInvestsByUserId(userId),
                Roadshows = InvestRepository.GetBusinessRoadshowByUserId(userId),
                CapitalRoadshows = InvestRepository.GetCapitalRoadshowByUserId(userId),
                Message = MessageRepository.GetLatestMessage(userId)
            };

            return View(model);
        }

        #endregion

        #region 申请贷款

        [Route("loan/{id?}")]
        public ActionResult ApplyLoan(long? id)
        {
            Loan model = null;

            if (id.HasValue)
            {
                model = LoanRepository.GetLoanById(id.Value);
                if (model != null)
                {
                this.ViewData["indus"] = new IndustryDropdown(model.Industry).Items;
            }
            else
            {
                model = new Loan { FoundingDate = DateTime.Now };
                this.ViewData["indus"] = new IndustryDropdown().Items;
            }
            }
            else
            {
                model = new Loan { FoundingDate = DateTime.Now };
                this.ViewData["indus"] = new IndustryDropdown().Items;
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SaveLoan(Loan loan)
        {
            this.ViewData["indus"] = new IndustryDropdown(loan.Industry).Items;

            var checkResult = CheckData();
            if (checkResult.Count>0)
            {
                return new JsonResult { Data = new { status = false, message = checkResult.Join(",") } };
            }

            if (loan.TeamAdv == null && loan.ProdAdv == null && loan.TechAdv == null && loan.ScaleAdv == null && loan.SaleAdv == null && loan.IndustryAdv == null && loan.ResourceAdv == null && loan.OtherAdv == null)
            {
                return new JsonResult { Data = new { status = false, message = "公司核心优势至少选填一个" } };
            }

            loan.UserId = User.Identity.GetUserId();
            loan.Status = ELoanAuditStatus.Submited;
            loan.UpdateDate = DateTime.Now;
            if (loan.Id == 0)
            {
                loan.ApplyTime = DateTime.Now;
            }

            var result =new LoanRepository().CreateOrUpdateLoan(loan);

            if (!result)
            {
                return new JsonResult { Data = new { status = false, message = "数据保存失败！" } };
            }

            return new JsonResult { Data = new { status = true, message = "" } };
        }

        [ActionName("loan-success")]
        public ActionResult LoanSuccess()
        {
            ViewBag.Message = "完成，借贷已成功提交。";
            return View("Success_Info", new ResultViewModel { ActionName = "index", ControllerName = "enterprise" });
        }
        #endregion

        #region 申请投资

        [Route("invest/{id}")]
        public ActionResult Invest(long id)
        {
            var invest = InvestRepository.GetInvestById(id);
            if (invest != null && invest.UserId == UserId)
            {
                // 阶段选择
                var stage = invest.IsFinished() ? EInvestAuditStage.First : invest.GetUserStage();
                switch (stage)
                {
                    case EInvestAuditStage.First:
                        return RedirectToAction("FirstAuditInfo");
                    case EInvestAuditStage.Second:
                        return RedirectToAction("SecondAuditInfo");
                    case EInvestAuditStage.Agreement:
                        return RedirectToAction("InvestAgreement");
                    case EInvestAuditStage.Roadshow:
                        return RedirectToAction("RoadshowIndex", "Roadshow", new { id });
                }
            }

            return RedirectToAction("FirstAuditInfo");
        }

        #region 一审
        [Route("invest-frist/{id?}")]
        public ActionResult FirstAuditInfo(long? id)
        {
            if (id == null)
            {
                var data = new InvestFirstAuditInfo { FoundingDate = DateTime.Now };
                this.ViewData["indus"] = new IndustryDropdown(data.Industry).Items;
                ViewBag.IsEditable = true;
                ViewBag.MaxStage = EInvestAuditStage.First;
                return View(data);           
            }
            else
            {
                var invest = InvestRepository.GetInvestById(id);
                if (invest == null || invest.UserId != UserId)
                {
                    return HttpNotFound();
                }

                this.ViewData["indus"] = new IndustryDropdown(invest.FirstAuditInfo.Industry).Items;
                ViewBag.IsEditable = invest.IsUserEditable(EInvestAuditStage.First);
                ViewBag.MaxStage = invest.GetUserStage();

                return View(invest.FirstAuditInfo);
            }            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("invest/submit-first-audit")]
        public ActionResult SaveFirstAuditInfo(InvestFirstAuditInfo info)
        {
            if (info.LegalPhone == null && info.LegalCellPhone == null)
            {
                ModelState.AddModelError("LegalCellPhone", "电话和手机必填一个");
            }

            if (info.ContactPhone == null && info.ContactCellPhone == null)
            {
                ModelState.AddModelError("ContactCellPhone", "电话和手机必填一个");
            }

            if (info.TeamAdv == null && info.ProdAdv == null && info.TechAdv == null && info.ScaleAdv == null && info.SaleAdv == null && info.IndustryAdv == null && info.ResourceAdv == null && info.OtherAdv == null)
            {
                ModelState.AddModelError("ResourceAdv", "公司核心优势必须至少填写一个");
            }

            //save data
            if (ModelState.IsValid)
            {
                if (info.Id == 0)
                {
                    var invest = new Invest
                    {
                        FirstAuditInfo = info,
                        UserId = UserId,
                        Stage = EInvestAuditStage.First,
                        Status = EInvestAuditStatus.Submited,
                        Reason = "提交初审",
                        ApplyTime = DateTime.Now,
                        UpdateTime = DateTime.Now
                    };

                    if (!InvestRepository.AddInvest(invest))
                    {
                        ModelState.AddModelError(string.Empty, "无法保存该申请，请检查有关数据是否合法有效。");
                    }
                }
                else
                {
                    //状态为审核中的申请,不能修改
                    var invest = InvestRepository.GetInvestById(info.Id);
                    if (invest.IsUserEditable(EInvestAuditStage.First))
                    {
                        invest.Stage = EInvestAuditStage.First;
                        invest.Status = EInvestAuditStatus.Submited;
                        invest.Reason = null;
                        invest.FirstAuditInfo = info;

                        if (!InvestRepository.UpdateInvest(invest))
                        {
                            ModelState.AddModelError(string.Empty, "无法保存该申请，请检查有关数据是否合法有效。");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "状态为审核中或审核完成的申请，不能修改。");
                    }
                }
            }

            if (!ModelState.IsValid)
            {
                this.ViewData["indus"] = new IndustryDropdown(info.Industry).Items;

Zkly.Web/Views/Enterprise/Index.cshtml
@model Zkly.BLL.ViewModels.EnterpriseViewModel

@Styles.Render("~/css/enterprise")
@Styles.Render("~/css/roadshow-item")

@{
    ViewBag.Title = "我的主页";
}

<div class="ly-container enterprise">
    <ol class="breadcrumb">
        <li><a href="/">首页</a></li>
        <li>我的主页</li>
    </ol>

    @{
        string message = "主题为空";

        if (Model.HasMessage())
        {
            if (!string.IsNullOrEmpty(Model.Message.Subject))
            {
                message = Model.Message.Subject;
            }

            <div class="message-panel">
                <div class="tip">
                    <img src="@Url.Content("~/Images/PublicImg/Btn-Volume-Up.png")" />
                    <span>最新消息</span>
                </div>

                <div class="message">
                    <img src="@Url.Content("~/Images/PublicImg/Btn-Warning.png")" />
                    <label>
                        消息提示：<span>@Html.Raw(message)</span>
                    </label>
                    <a class="btn btn-default" href="@Url.Action("MessageCenter", "Enterprise", new { state = false })" role="button">点击进入</a>
                </div>
            </div>
        }
    }

    <div class="invest">
        <div class="section-title">
            <span>我的投资</span>
            <a class="btn btn-primary" href="@Url.Action("FirstAuditInfo")">我要申请投资</a>
        </div>
        <div>
            <table class="table table-striped">
                <tr class="table-header">
                    <td class="col-1">申请日期</td>
                    <td class="col-2">项目名称</td>
                    <td class="col-3">申请资金(万元)</td>
                    <td class="col-4">阶段状态</td>
                    <td class="col-5">更新时间</td>
                    <td class="col-6">操作</td>
                </tr>
                @if (Model.Invests.Count == 0)
                {
                    <tr>
                        <td colspan="7"><p>您目前还没有投资申请！</p></td>
                    </tr>
                }
                else
                {
                    foreach (var item in Model.Invests)
                    {

                        <tr>
                            <td class="col-1">@item.ApplyTime.ToString("yyyy-MM-dd")</td>
                            <td class="col-2">@item.FirstAuditInfo.ProjectName</td>
                            <td class="col-3">@item.FirstAuditInfo.ApplyQuota</td>
                            <td class="col-4">@item.GetStatusDescription()</td>
                            <td class="col-5">@Html.DisplayFor(m => @item.UpdateTime)</td>
                            <td class="col-6">
                                <a class="btn btn-primary btn-sm" href="@Url.Action("Invest", new { item.Id })">点击进入</a>
                            </td>
                        </tr>
                    }
                }
            </table>
        </div>
    </div>

    <div class="loan">
        <div class="section-title">
            <span>我的贷款</span>
            <a class="btn btn-primary" href="@Url.Action("loan")">我要申请贷款</a>
        </div>
        <table class="table table-striped">
            <tr class="table-header">
                <td class="col-1">申请日期</td>
                <td class="col-2">项目名称</td>
                <td class="col-3">申请资金(万元)</td>
                <td class="col-4">状态</td>
                <td class="col-5">更新时间</td>
                <td class="col-6">操作</td>
            </tr>

            @if (Model.Loans.Count == 0)
            {
                <tr>
                    <td colspan="6"><p>您目前还没有贷款申请！</p></td>
                </tr>
            }
            else
            {
                foreach (var item in Model.Loans)
                {
                    <tr>
                        <td class="col-1">@item.ApplyTime.ToString("yyyy-MM-dd")</td>
                        <td class="col-2">@item.ProjectName</td>
                        <td class="col-3">@item.ApplyQuota</td>
                        <td class="col-4">@Html.DisplayFor(m => item.Status)</td>
                        <td class="col-5">@item.UpdateDate</td>
                        <td class="col-6">
                            <a class="btn btn-primary btn-sm" href="@Url.Action("ApplyLoan", new { item.Id })">点击进入</a>
                        </td>
                    </tr>
                }
            }
        </table>
    </div>

    <div class="my-roadshow">
        <div class="section-title">
            <span>我的路演 </span>
        </div>
        <div role="tabpanel">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active">
                    <a href="#biz" aria-controls="biz" role="tab" data-toggle="tab">业务路演</a>
                </li>
                <li role="presentation">
                    <a href="#capital" aria-controls="capital" role="tab" data-toggle="tab">资本路演</a>
                </li>
            </ul>
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane roadshow active" id="biz">
                    @if (Model.Roadshows.Count == 0)
                    {
                        <div class="no-data-tip">目前还没有上传业务路演！</div>
                    }
                    else
                    {
                        <ul>
                            @foreach (var item in Model.Roadshows)
                            {
                                if (item != null)
                                {
                                    <li>
                                        @Html.Partial("Template/RoadshowItemForEdit", item)
                                    </li>
                                }
                            }
                        </ul>
                        <div class="clearfix"></div>
                    }
                </div>
                <div role="tabpanel" class="tab-pane roadshow" id="capital">
                    @if (Model.CapitalRoadshows.Count == 0)
                    {
                        <div class="no-data-tip">目前还没有资本路演！</div>
                    }
                    else
                    {
                        <ul>
                            @foreach (var item in Model.CapitalRoadshows)
                            {
                                if (item != null)
                                {
                                    <li>
                                        @Html.Partial("Template/CapitalRoadshowItem", item)  @*todo*@
                                    </li>
                                }
                            }
                        </ul>
                        <div class="clearfix"></div>
                    }
                </div>
            </div>

        </div>
    </div>
</div>

Zkly.Web/Views/Enterprise/InvestAgreement.cshtml
@model Zkly.BLL.ViewModels.InvestAgreementViewModel


@section heads{

    @Styles.Render("~/css/invest")
}



<div class="invest">
    @Html.Partial("_InvestTop", EInvestAuditStage.Agreement)

    <div id="invest-agreement" class="panel panel-default">
        <div class="panel-body">
            <div class="panel panel-primary">
                <div class="panel-heading">协议选择</div>
                <div class="panel-body">
                    @using (Html.BeginForm("SaveInvestAgreement", "Enterprise", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(m => m.InvestId)


                        if (!string.IsNullOrEmpty(Model.ErrorInfo))
                        {
                            <div class="alert alert-danger alert-dismissible" role="alert">

                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">关闭</span>
                                </button>


                                @Html.ValidationSummary(false, "", new { @class = "bg-danger" })
                            </div>
                        }

                        <div class="form-group">
                            @{

                        string oneMonth = string.Empty;
                        string twoMonth = string.Empty;
                        string threeCheckMonth = string.Empty; ;
                        if (Model.InvestAgreement != null && Model.InvestAgreement.LockMonth == 1)
                        {
                            oneMonth = "active";
                        }
                        else if (Model.InvestAgreement != null && Model.InvestAgreement.LockMonth == 2)
                        {
                            twoMonth = "active";
                        }
                        else if (Model.InvestAgreement != null && Model.InvestAgreement.LockMonth == 3)
                        {
                            threeCheckMonth = "active";
                        }

                            }

                            @Html.Label("", "锁定期", new { @class = "col-xs-2 control-label" })
                            <div class="col-xs-10">
                                <div class="btn-group" data-toggle="buttons">
                                    <label class="btn btn-default @oneMonth">
                                        @Html.RadioButton("LockMonth", 1, false, new { @class = "form-control" }) 一个月
                                    </label>
                                    <label class="btn btn-default @twoMonth">
                                        @Html.RadioButton("LockMonth", 2, false, new { @class = "form-control" }) 两个月
                                    </label>
                                    <label class="btn btn-default @threeCheckMonth">
                                        @Html.RadioButton("LockMonth", 3, false, new { @class = "form-control" }) 三个月
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            @{
                        int agencyCommissionId = 0;

                        if (Model.InvestAgreement != null && Model.InvestAgreement.AgencyCommission != null)
                        {
                            agencyCommissionId = Model.InvestAgreement.AgencyCommission.Id;
                        }
                            }

                            @Html.Label("", "佣金", new { @class = "col-xs-2 control-label" })
                            <div class="col-xs-10">
                                <div class="col-xs-2">现金交易</div>
                                <div class="col-xs-10">
                                    <ul class="list-inline">
                                        @foreach (var item in Model.CashOptions)
                                        {
                                            bool isCheck = item.Id == agencyCommissionId;

                                            <li>
                                                @Html.RadioButton("AgencyCommissionId", item.Id, @isCheck) @item.CashPercent.ToString("P0");
                                            </li>
                                        }
                                    </ul>
                                </div>

                                <div class="col-xs-2">股权交易</div>
                                <div class="col-xs-10">
                                    <ul class="list-inline">
                                        @foreach (var item in Model.StockOptions)
                                        {
                                            bool isCheck = item.Id == agencyCommissionId;

                                            <li>
                                                @Html.RadioButton("AgencyCommissionId", item.Id, @isCheck) @item.StockPercent.ToString("P0");
                                            </li>
                                        }
                                    </ul>
                                </div>

                                <div class="col-xs-2">现金及股权交易</div>
                                <div class="col-xs-10">
                                    <ul class="list-unstyled">
                                        @foreach (var item in Model.CombineOptions)
                                        {
                                            bool isCheck = item.Id == agencyCommissionId;

                                            <li>
                                                @Html.RadioButton("AgencyCommissionId", item.Id, @isCheck) @item.Description;
                                            </li>
                                        }
                                    </ul>
                                </div>

                            </div>
                        </div>


                        <br /><br />
                        <div class="form-group">
                            @Html.Label("", "协议上传", new { @class = "col-xs-2 control-label" })
                            <div class="col-xs-10">

                                <input id="file" type="file" name="investAgreement" />
                                <br />

                                @if (Model.InvestAgreement != null && Model.InvestAgreement.AgreementFile != null)
                                {
                                    <span class="text-success">文件名： @Model.InvestAgreement.AgreementFile.FileName</span>
                                    <a href="@Url.Action("FileDownLoad", "File", new { id = Model.InvestAgreement.AgreementFile.Id })">下载文件</a>
                                }

                            </div>
                        </div>

                        <br />

                        @*<div class="form-group">
                                <div class="col-xs-2"></div>
                                <div class="col-xs-10">
                                    @Html.CheckBox("AgreementChecked", false) 我已阅读并同意签署《XXXX协议》
                                </div>
                            </div>*@


                        if (ViewBag.IsEditable!=null&&ViewBag.IsEditable)
                        {
                            <div class="form-group">
                                <div class="col-xs-2"></div>
                                <div class="col-xs-10">
                                    <input type="submit" id="investAgreement_save" class="btn btn-primary btn-block" value="保 存" />
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>

            <hr />

            @*<div class="panel panel-primary">
                    <div class="panel-heading">协议上传</div>
                    <div class="panel-body">
                        <div class="col-xs-2"></div>
                        <div class="col-xs-10">
                            @using (Html.BeginForm("UploadInvestAgreement", "Enterprise", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.HiddenFor(m => m.InvestId)
                                <div class="input-group">

                                    <span class="btn btn-default btn-file">
                                        浏     览... <input id="file" type="file" name="investAgreement" />
                                    </span>
                                    <br/><br />
                                    <span class="input-group-addon">浏览文件：</span>
                                    <input type="text" class="form-control" placeholder="打开已签署完毕的协议扫描件" aria-describedby="basic-addon1">
                                    <input type="submit" class="btn btn-primary" value="上传协议" />
                                </div>
                            }
                        </div>

                    </div>
                </div>*@
        </div>
    </div>

</div>



@section scripts{

    @Scripts.Render("~/js/invest-agreement")
    @Scripts.Render("~/js/enterprise-invest")
}