Zkly.Admin.Web/Models/InvestViewModel.cs
using PagedList;

using Zkly.DAL.Models;

namespace Zkly.Admin.Web.Models
{
    public class InvestViewModel
    {
        public Invest Invest { get; set; }
      
        public string ProjectSource { get; set; }

        //知识产权形式
        public string IpRform { get; set; }

        //资信证明
        public long CreditCertificateFile { get; set; }

        //机构代码证
        public long IdOrganizationFile { get; set; }

        //身份证正面
        public long IdCardFrontFile { get; set; }

        //身份证反面
        public long IdCardBackFile { get; set; }

        //营业执照
        public long BusinessLicenseFile { get; set; }

        //商业计划书
        public long BusinessPlanFile { get; set; }

        //税务登记
        public long TaxRegistrationFile { get; set; }

        //证明书
        public long ManualFile { get; set; }

        //附件1
        public long Accessory1File { get; set; }

        //附件2
        public long Accessory2File { get; set; }

        //附件3
        public long Accessory3File { get; set; }
    }

    public class TempFolderModel
    {
        public IPagedList<InvestTempFolder> ListTempFolder { get; set; }
    }
}

Zkly.Admin.Web/Controllers/FileController.cs
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;
using Zkly.BLL.Repositories;
using Zkly.Common;
using Zkly.Common.Mvc.UI;
using Zkly.DAL.Models;

namespace Zkly.Admin.Web.Controllers
{
    [Authorize]
    public class FileController : Controller
    {
        [Route("get-file-{id}")]
        public ActionResult DownLoad(long id)
        {
            UploadFileInfo uploadFile = new UploadFileInfoRepository().GetUploadFileInfoById(id);
            if (uploadFile != null)
            {
                return File(FileHelper.GetFilePath(uploadFile.FilePath), FileHelper.GetFileContentType(uploadFile.FileName), uploadFile.FileName);
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        /// 通过传图片表中的主键Id进行图片显示
        /// </summary>
        /// <param name="id">文件表中的主键Id</param>
        /// <returns>返回图片流对象</returns>
        [Route("get-img-{id}")]
        public ActionResult FileDisplayById(long id)
        {
            UploadFileInfo uploadFile = new UploadFileInfoRepository().GetUploadFileInfoById(id);
            if (uploadFile != null)
            {
                return File(
                    FileHelper.GetFilePath(uploadFile.FilePath),
                    FileHelper.GetFileContentType(uploadFile.FileName));
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        /// 通过传图片表中的路径进行图片显示
        /// </summary>
        /// <param name="path">文件表中的主键Id</param>
        /// <param name="fileName">文件名称</param>
        /// <returns>返回图片流对象</returns>
        public ActionResult FileDisplayByPath(string path, string fileName)
        {
            return File(
                ConfigurationManager.AppSettings["UploadFolder"] + "/TempFolder/" + path,
                FileHelper.GetFileContentType(fileName));
        }

        public ActionResult ShowPartial(long investSecondAuditId, long typeId)
        {
            long? uploadFileInfoId = new InvestSecondAuditFileReponsitory().GetInvestSecondAuditFile(
                investSecondAuditId,
                typeId);

            if (uploadFileInfoId.HasValue)
            {
                UploadFileInfo uploadFileInfo = new UploadFileInfoRepository().GetUploadFileInfoById(uploadFileInfoId.Value);

                //是否是图片
                ViewBag.IsImg = false;
                if (uploadFileInfo != null && uploadFileInfo.FileName != null)
                {
                    ViewBag.IsImg = FileHelper.IsImage(uploadFileInfo.FileName);
                }

                return View(uploadFileInfo);
            }

            return View();
        }
    }
}

Zkly.Admin.Web/Controllers/InvestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

using PagedList;

using Zkly.BLL.Repositories;
using Zkly.BLL.Services;
using Zkly.BLL.ViewModels;
using Zkly.Common;
using Zkly.Common.Mvc.Attribute;
using Zkly.Common.Utils;
using Zkly.DAL.Models;

namespace Zkly.Admin.Web.Controllers
{
    public class InvestController : BaseController
    {
        private int pageSize = 30;
        private InvestRepository investRepository = new InvestRepository();

        /// <summary>
        /// 审批列表
        /// </summary>
        [Route("invest-{stage=First}/{state?}")]
        public ActionResult AuditList(int? page, EInvestAuditStage stage, string state, int?grade=null)
        {
            ViewBag.Stage = stage;
            ViewBag.State = state;

            int pageNumber = page ?? 1;

            if (string.IsNullOrEmpty(state))
            {
                return View(investRepository.GetInvestsByStage(stage).ToPagedList(pageNumber, pageSize));
            }

            var invests = new List<Invest>();

            if (state == FilterType.Immediately)
            {
                invests = investRepository.GetImmediatelyInvests(stage);
            }
            else if (state == FilterType.Waiting)
            {
                invests = investRepository.GetWaitingInvest(stage);
            }
            else if (state == FilterType.Temporarily)
            {
                invests = investRepository.GetTemporaryInvests(stage);
            }
            else if (state == FilterType.UnSubmited)
            {
                var model = investRepository.GetInvests(stage, EInvestAuditStatus.NotStarted).ToPagedList(pageNumber, pageSize);
                return View(model);
            }

            //用来筛选一审企业资金级别
            if (stage == EInvestAuditStage.First)
            {
                invests = invests.FilterGrade(grade);
            }

            return View(invests.ToPagedList(pageNumber, pageSize));
        }

        [RestoreModelState]
        [Route("audit-detail-{stage}/{id}", Name = "audit-detail")]
        public async Task<ActionResult> AuditDetails(int id, EInvestAuditStage stage, bool isedit = false)
        {
            var invest = investRepository.GetInvestById(id);

            //如果是刚提交的申请，需要改变它的状态到：审批中
            if (stage < EInvestAuditStage.Roadshow && invest.Stage == stage && invest.Status == EInvestAuditStatus.Submited)
            {
                invest.AuditQuota = null;
                invest.Status = EInvestAuditStatus.Auditing;
                invest.Reason = "查阅审批";
                investRepository.UpdateInvest(invest, UserId);

                var prjName = invest.FirstAuditInfo.ProjectName;
                var stageDesc = invest.Stage.Description();
                var subject = string.Format("项目:{0} 已经进入{1}审批环节", prjName, stageDesc);
                var message = string.Format("尊敬的用户，您好！您的投资申请项目:{0} 已经进入{1}审批环节。请随时关注审批状态变化，谢谢！", prjName, stageDesc);
                await UserManager.SendAllMessagesAsync(invest.UserId, subject, message);
            }

            var model = new InvestAuditViewModel
            {
                Invest = investRepository.GetInvestById(id),
                Stage = stage
            };

            ViewData["isedit"] = isedit;

            return Request.IsAjaxRequest()
             ? View("AuditDetailTab", model)
             : View("AuditDetails", model);
        }

        [HttpPost]
        [SetModelState]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveAudit(AuditResult auditResult)
        {
            var invest = investRepository.GetInvestById(auditResult.InvestId);
            if (!invest.IsAuditable(auditResult.Stage))
            {
                var statusDesc = invest.GetStatusDescription();
                var stageDesc = auditResult.Stage.Description();
                ModelState.AddModelError("", string.Format("该申请当前处于{0}状态，不可做{1}审批。", statusDesc, stageDesc));
            }
            else if (ModelState.IsValid)
            {
                #region 变更状态
                if (auditResult.IsPass)
                {
                    if (auditResult.AuditQuota > 0)
                    {
                        invest.AuditQuota = auditResult.AuditQuota;
                    }

                    invest.Status = EInvestAuditStatus.Accepted;
                    invest.Reason = null;
                }
                else
                {
                    invest.AuditQuota = null;
                    invest.Status = EInvestAuditStatus.Rejected;
                    invest.Reason = auditResult.Reason;
                }
                #endregion

                if (investRepository.UpdateInvest(invest, UserId))
                {
                    #region 发送审批消息
                    var prjName = invest.FirstAuditInfo.ProjectName;
                    var stageDesc = invest.Stage.Description();
                    var statusDesc = invest.Status.Description();
                    var subject = string.Format("项目:{0}，{1}审批{2}", prjName, stageDesc, statusDesc);
                    statusDesc = auditResult.IsPass ? "已经通过了" : "被拒绝了，失败原因：" + auditResult.Reason;
                    var message = string.Format("尊敬的用户，您好！您的投资申请项目:{0}，在{1}审批环节{2}。请随时关注审批状态变化，谢谢！", prjName, stageDesc, statusDesc);
                    await UserManager.SendAllMessagesAsync(invest.UserId, subject, message);
                    #endregion

                    //#region 协议结束，自动进入路演

                    //if (invest.Stage == EInvestAuditStage.Agreement && invest.Status == EInvestAuditStatus.Accepted)
                    //{
                    //    invest.Stage = EInvestAuditStage.Roadshow;
                    //    invest.Status = EInvestAuditStatus.Submited;
                    //    invest.Reason = "自动进入路演阶段";
                    //    investRepository.UpdateInvest(invest, UserId);
                    //}
                    //#endregion
                }
                else
                {
                    ModelState.AddModelError("", "数据保存失败，请检查相关数据是否有效。");
                }
            }

            return ModelState.IsValid
                ? RedirectToAction("AuditList", new { stage = auditResult.Stage, state = auditResult.FilterType })
                : RedirectToAction("AuditDetails", new { invest.Id, auditResult.Stage });
        }

        [AjaxOnly]
        public ActionResult History(int id)
        {
            var model = investRepository.GetInvestHistoryById(id);
            return View("AuditHistoryTab", model);
        }

        [Route("invest-import")]
        public ActionResult Import()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveImport(HttpPostedFileBase excelFile)
        {
            var model = new Dictionary<int, Invest>();
            if (ModelState.IsValid)
            {
                if (excelFile == null)
                {
                    ModelState.AddModelError("", "请选择上传的Excel文件！");
                    return View("Import", model);
                }

                //读取上传excel 的数据
                var table = ExcelUtil.ReadTable(excelFile.InputStream, excelFile.FileName.ToLower().EndsWith(".xlsx"));
                if (table == null || table.Rows.Count == 0)
                {
                    ModelState.AddModelError("", "没有相关数据，请上传一个有效的表格。");
                }
                else
                {
                    var users = table.ColumnToList<string>("用户名");
                    var investFirstAuditLists = table.CastToList<InvestFirstAuditInfo>();
                    var recordId = 0;
                    foreach (var userName in users)
                    {
                        var firstInfo = investFirstAuditLists[recordId++];
                        try
                        {
                            //var user = await UserManager.FindByNameAsync(userName); //会导致EF 多个dbcontext异常
                            var user = investRepository.FirstOrDefault<ApplicationUser>(u => u.UserName == userName);
                            if (user == null)
                            {
                                ModelState.AddModelError(string.Format("记录{0}异常：", recordId), string.Format("无法找到用户名为：{0}的相关记录。", userName));
                            }
                            else
                            {
                                var invest = new Invest
                                {
                                    FirstAuditInfo = firstInfo,
                                    UserId = user.Id,
                                    Stage = EInvestAuditStage.First,
                                    Status = EInvestAuditStatus.NotStarted,
                                    Reason = "批量导入",
                                    ApplyTime = DateTime.Now,
                                    UpdateTime = DateTime.Now
                                };

                                if (!investRepository.AddInvest(invest, UserId))
                                {
                                    ModelState.AddModelError(string.Format("记录{0}异常：", recordId), "数据库保存失败，请检查该记录的数据是否合法有效。");
                                }
                                else
                                {
                                    //invest.User = user;
                                    model.Add(recordId, invest);
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            ModelState.AddModelError(string.Format("记录{0}异常：", recordId), ex.Message);
                        }
                    }

                    AddSuccessMessage("导入完成：", string.Format("已读取{0}条记录，成功导入{1}条一审材料。", table.Rows.Count, model.Count));
                }

Zkly.Admin.Web/Controllers/TempFolderController.cs
using System;
using System.Collections.Generic;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;

using PagedList;

using Zkly.BLL.Repositories;
using Zkly.BLL.ViewModels;
using Zkly.Common.Utils;
using Zkly.DAL.Context;
using Zkly.DAL.Models;

namespace Zkly.Admin.Web.Controllers
{
    [RoutePrefix("tempFolder")]
    public class TempFolderController : Controller
    {
        private InvestTempFolderRepository investTempFolderRepository = new InvestTempFolderRepository();
        private int pageSize = 10;

        [Route("first-audits/{page?}")]
        public ActionResult FirstAudit(int? page)
        {
            int pageNumber = page ?? 1;
            var model = new TempFolderModel
            {
                ListTempFolder = investTempFolderRepository.ListInvestTempFolder(EInvestAuditStage.First).ToPagedList(pageNumber, pageSize)
            };

            return View(model);
        }

        [Route("second-audits/{page?}")]
        public ActionResult SecondAudit(int? page)
        {
            int pageNumber = page ?? 1;
            var model = new TempFolderModel
            {
                ListTempFolder = investTempFolderRepository.ListInvestTempFolder(EInvestAuditStage.Second).ToPagedList(pageNumber, pageSize)
            };
            return View(model);
        }

        //放置暂存文件夹
        public JsonResult PlaceTempFolder(string investId)
        {
            if (string.IsNullOrEmpty(investId))
            {
                return new JsonResult { Data = new { status = true, message = "没有任何选项！" } };
            }

            var listInvestTempFolder = new List<InvestTempFolder>();
            var listIntInvestId = investId.Split(',').Select(a => Convert.ToInt32(a)).ToList();

            for (int i = 0; i < listIntInvestId.Count; i++)
            {
                listInvestTempFolder.Add(new InvestTempFolder
                {
                    InvestId = listIntInvestId[i],
                    UserId = User.Identity.GetUserId(),
                    CreateTime = DateTime.Now
                });
            }

            bool result = investTempFolderRepository.AddOrUpdateMultiple(listInvestTempFolder);

            return new JsonResult { Data = new { status = result, message = result ? "提交成功！" : "提交时发生错误！" } };
        }

        //删除暂存文件夹
        public JsonResult DeleteTempFolder(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new JsonResult { Data = new { status = true, message = "没有任何选项！" } };
            }

            var listIntInvestId = id.Split(',').ToList();
            bool result = investTempFolderRepository.DeleteInvestTempFolder(listIntInvestId);
            return new JsonResult { Data = new { status = result, message = result ? "提交成功！" : "数据提交时发生错误！" } };
        }
    }
}

Zkly.Admin.Web/Views/Invest/AuditDetailTab.cshtml
@model Zkly.BLL.ViewModels.InvestAuditViewModel
<div role="tabpanel" class="tab-pane @(IsAjax ? "" : "active") row" id="invest-@Model.Stage">
    <div class="col-md-8">
        @switch (Model.Stage)
        {
            case EInvestAuditStage.First:
                @Html.Partial("FirstAuditInfo", Model.Invest.FirstAuditInfo)
                break;
            case EInvestAuditStage.Second:
            @Html.Partial("SecondAuditInfo", Model.Invest.SecondAuditInfo)
                break;
            case EInvestAuditStage.Agreement:
            @*<div class="jumbotron alert alert-warning text-center" role="alert">
                <p>&nbsp;</p>
                <h1>
                    <span class="fa fa-ban" aria-hidden="true"></span> 功能未开放
                </h1>
                <p>&nbsp;</p>
                <p>暂不支持签订协议功能，请直接进入终（路演）页面。</p>
                <p>&nbsp;</p>
                <p>&nbsp;</p>
                <p>&nbsp;</p>
                <p>&nbsp;</p>
            </div>*@
             @Html.Partial("InvestAgreement", Model.Invest.Agreement)
                break;
            case EInvestAuditStage.Roadshow:

                if (Model.Invest.CapitalRoadshow == null || (Model.Invest.CapitalRoadshow != null && !Model.Invest.CapitalRoadshow.RecordState) || (bool)@ViewData["isedit"])
                {
                    using (Html.BeginForm("Save", "CapitalRoadshow", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data", @id = "info-form" }))
                    {
                        @Html.Partial("CapitalRoadshow/_Edit", (Model.Invest.CapitalRoadshow == null || (Model.Invest.CapitalRoadshow != null && !Model.Invest.CapitalRoadshow.RecordState)) ? new CapitalRoadshow { Id = 0, StartDate = DateTime.Now.AddHours(-1), EndDate = DateTime.Now, CompanyName = Model.Invest.FirstAuditInfo.CompanyName } : Model.Invest.CapitalRoadshow)
                        <div class="panel-footer">
                            <div class="col-xs-offset-2">
                                <input type="submit" class="btn btn-primary" value="保存" />
                                <a href="@Url.Action("AuditDetails", "Invest", new {id = Model.Invest.Id, stage = EInvestAuditStage.Roadshow})" class="btn btn-primary">返回列表</a>
                            </div>
                        </div>
                    }
                }
                else
                {
                    @Html.Partial("_Details", Model.Invest.CapitalRoadshow)
                }

                @*<div class="jumbotron alert alert-success text-center" role="alert">
                        <p>&nbsp;</p>
                        <h1><span class="fa fa-warning" aria-hidden="true"></span> 无相关资料</h1>
                        <p>&nbsp;</p>
                        <p>终审无相关资料，请直接审批金额。</p>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                    </div>*@


                break;
        }
    </div>
    @if (Model.Stage != EInvestAuditStage.Roadshow)
    {
        <div class="col-md-4">
            <div data-spy="affix" data-offset-top="125">
                @(Model.Invest.IsAuditable(Model.Stage)
                      ? Html.Partial("_AuditAction", Model.Invest)
                      : Html.Partial("_AuditResult", Model.Invest))
            </div>
        </div>

    }
</div>

Zkly.Admin.Web/Views/Invest/AuditList.cshtml
@model PagedList.IPagedList<Zkly.DAL.Models.Invest>
@using PagedList.Mvc;
@using Zkly.Common;
@{
    ViewBag.Title = "申请资料列表";
}
@section styles{
    @Styles.Render("~/style/invest")
}
<div class="panel panel-default ">
    <div class="panel-heading">
        <ul class="nav nav-pills nav-justified">
            <li role="presentation" class="@Html.Raw(ViewBag.State == FilterType.Waiting ? "active" : "")">
                <a href="@Url.Action("AuditList", "Invest", new {state = FilterType.Waiting, stage = ViewBag.Stage})">所有待审批申请</a>
            </li>
            <li role="presentation" class="@Html.Raw(ViewBag.State == FilterType.Immediately ? "active" : "")">
                <a href="@Url.Action("AuditList", "Invest", new {state = FilterType.Immediately, stage = ViewBag.Stage})">立即处理申请</a>
            </li>
            <li role="presentation" class="@Html.Raw(ViewBag.State == FilterType.Temporarily ? "active" : "")">
                <a href="@Url.Action("AuditList", "Invest", new {state = FilterType.Temporarily, stage = ViewBag.Stage})">暂存文件夹申请</a>
            </li>
            @if (ViewBag.Stage == EInvestAuditStage.First)
            {
                <li role="presentation" class="@Html.Raw(ViewBag.State == FilterType.UnSubmited ? "active" : "")">
                    <a href="@Url.Action("AuditList", "Invest", new { state = FilterType.UnSubmited, stage = ViewBag.Stage })">未提交的申请</a>
                </li>
            }
            <li role="presentation" class="@Html.Raw(string.IsNullOrEmpty(ViewBag.State) ? "active" : "")">
                <a href="@Url.Action("AuditList", "Invest", new { stage = ViewBag.Stage,state="" })">所有申请</a>
            </li>
        </ul>
    </div>

    @if (Model.Count == 0)
    {
        <div id="container" class="panel-body">
            <div class="jumbotron alert alert-warning text-center" role="alert">
                <h1><span class="fa fa-exclamation-circle" aria-hidden="true"></span> 目前还没有申请资料</h1>
            </div>
        </div>
    }
    else
    {
        <table name="audit" class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" alt="全选" id="btnCheckAll" />
                    </th>
                    <th>申请日期</th>
                    <th>公司</th>
                    <th>项目</th>
                    <th>申请资金</th>
                    <th>阶段状态</th>
                    <th>申请时间</th>
                    <th>更新时间</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @if (item.IsAuditable())
                            {
                                <input type="checkbox" name="chkItem" value="@item.Id" />
                            }
                        </td>
                        <td>@item.ApplyTime.ToString("yyyy-MM-dd")</td>
                        <td>@item.FirstAuditInfo.CompanyName</td>
                        <td>
                            <a href="@Url.Action("AuditDetails", "Invest", new {id = @item.Id, stage=ViewBag.Stage})" target="_blank">
                                @item.FirstAuditInfo.ProjectName
                            </a>
                        </td>
                        <td>@string.Format("{0:N0} 万元", item.FirstAuditInfo.ApplyQuota)</td>
                        <td>@item.GetStatusDescription()</td>
                        <td>@Html.DisplayFor(m => item.ApplyTime)</td>
                        <td>@Html.DisplayFor(m => item.UpdateTime)</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    <div class="panel-footer">
        @if (ViewBag.Stage == EInvestAuditStage.First)
        {

            @Html.ActionLink("百万级企业", "AuditList", "Invest", new { state = ViewBag.State, stage = ViewBag.Stage, grade = (int)EInvestGrade.Million }, new { @class = "btn btn-primary" })
            
            @Html.ActionLink("千万级企业", "AuditList", "Invest",new { state = ViewBag.State, stage = ViewBag.Stage, grade = (int)EInvestGrade.TenMillion },new { @class = "btn btn-primary" })

            @Html.ActionLink("导入一审资料", "Import", null, new { @class = "btn btn-primary" })
        }
        @if (ViewBag.State == FilterType.Temporarily)
        {
            <input type="button" class="btn btn-primary" value="移入立即处理申请" id="deleteTempFolder" data-post-url="@Url.Action("DeleteTempFolder", "TempFolder")" />
        }
        else
        {
            <input type="button" class="btn btn-primary" value="放置暂存文件夹" id="placeTempFolder" data-post-url="@Url.Action("PlaceTempFolder", "TempFolder"))" />
        }
        <div class="pull-right">
            @Html.DisplayPagination(page => Url.Action("AuditList", "invest", new { stage = ViewBag.Stage, state = ViewBag.State, page }))
        </div>
    </div>
</div>



@section scripts{
    @Scripts.Render("~/js/placeTempFolder")
    @Scripts.Render("~/js/deleteTempFolder")
}

Zkly.Admin.Web/Views/Invest/Import.cshtml
@model IDictionary<int, Invest>
@{
    ViewBag.Title = "批量导入一审资料";
}

@using (Html.BeginForm("SaveImport", "Invest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                上传一审资料表格
            </h3>
        </div>
        @Html.Partial("_SuccessMessage")
        @Html.Partial("_ErrorMessage")
        <div class="panel-body">
            @if (Model != null && Model.Count != 0)
            {
                <table class="table table-striped">
                    <tr>
                        <th>
                            行号
                        </th>
                        <th>
                            用户名
                        </th>
                        <th>
                            公司名称
                        </th>
                        <th>
                            项目名称
                        </th>
                        <th>
                            联系人
                        </th>
                        <th>
                            联系人手机
                        </th>
                        <th>&nbsp;</th>
                    </tr>

                    @foreach (var kvp in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => kvp.Key)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => kvp.Value.User.UserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => kvp.Value.FirstAuditInfo.CompanyName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => kvp.Value.FirstAuditInfo.ProjectName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => kvp.Value.FirstAuditInfo.Contact)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => kvp.Value.FirstAuditInfo.ContactCellPhone)
                            </td>
                            <td>
                                @Html.ActionLink("查看", "AuditDetails", new { id = kvp.Value.Id, stage = EInvestAuditStage.First }, new { target = "_blank" })
                            </td>
                        </tr>
                    }
                </table>
            }

            <div class="bg-info" style="padding: 15px;">
                <p>请选择包含一审资料的Excel文件，文件格式如下图所示：</p>
                <hr />
                <p> <img src="~/Images/import-invests-excel-sample.png" alt="Excel的内容格式样例" style="width:100%"></p>
            </div>
            <hr />
            <div class="col-xs-5">
                <input type="file" name="excelFile" accept=".xlsx" style="float:left;margin-right:5px;" />
                <a href="~/Files/企业项目列表_数据导入用 .xlsx" class="btn btn-success" style="float:left">下载模板</a>
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="提交" class="btn btn-primary" />
            <a href="@Url.Action("AuditList")" class="btn btn-default">返回列表</a>
        </div>
    </div>
}





 

Zkly.Admin.Web/Views/Invest/_AuditAction.cshtml
@model Invest
@using Microsoft.AspNet.Identity
@using Zkly.Common.Extension

@{
    var requestStage = this.ViewContext.RouteData.Values["stage"].ToString().ToEnum<EInvestAuditStage>();
}

@using (Html.BeginForm("SaveAudit", "Invest"))
{
    <div id="invest-audit-panel" class="panel panel-default">

        <div class="panel-heading">
            审批
        </div>

        <div class="panel-body">
            @Html.AntiForgeryToken()
            <input type="hidden" value="@Model.Id" name="AuditId" />
            <input type="hidden" value="@Model.Stage" name="Stage" />
            <input type="hidden" value="@Model.UserId" name="UserId" />
            <input type="hidden" value="@Model.Id" name="InvestId" />
            <input type="hidden" value="1" name="AuditType" />
            <input type="hidden" value="@ViewBag.State" name="FilterType" />

            <div class="btn-group btn-group-justified" data-toggle="buttons">
                <label class="btn btn-default">
                    <input type="radio" name="IsPass" id="pass" value="true" autocomplete="off"> 通过
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="IsPass" id="fail" value="false" autocomplete="off"> 拒绝
                </label>
            </div>

            <div id="audit-quota" style="display:none">
                <span>批复金额（万元）：</span>
                <input name="AuditQuota" class="form-control" type="text" placeholder="@Model.FirstAuditInfo.ApplyQuota" />
            </div>

            <div id="audit-reason" style="display: none;">
                <span>拒绝原因：</span>
                <textarea name="Reason" class="form-control" type="text" placeholder="拒绝的原因"></textarea>
            </div>
        </div>

        <div class="panel-footer">
            <button type="submit" id="save-audit" class="btn btn-primary" disabled="disabled"><span class="fa fa-save" aria-hidden="true"></span> 保存</button>
            <input style="display: none" type="checkbox" name="chkItem" checked="checked" value="@Model.Id"/>
            <input type="button" class="btn btn-primary" value="放入暂存文件夹" id="placeTempFolder" data-request-url="@Url.Action("AuditList", "Invest", new {stage = requestStage, state = ViewBag.State})" data-post-url="@Url.Action("PlaceTempFolder", "TempFolder")" />
            <a class="btn btn-default" href="@Url.Action("AuditList", "Invest", new {stage = requestStage, state = ViewBag.State})"><span class="fa fa-arrow-left" aria-hidden="true"></span> 返回列表</a>
        </div>
    </div>
}