Zkly.Admin.Web/Controllers/SmsController.cs
using System.Web.Mvc;
using Zkly.Common.SMS;

namespace Zkly.Admin.Web.Controllers
{
    [Authorize]
    public class SmsController : Controller
    {
        // GET: Sms/Register
        public ActionResult Register()
        {
            return View("Register");
        }

        // POST: Sms/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(string userName, string mobile, string phone, string fax, string email, string postcode, string company, string address)
        {
            if (!ModelState.IsValid)
            {
                return View("Register");
            }

            var client = new SmsClient();
            var model = client.Register(userName, mobile, phone, fax, email, postcode, company, address);
            return View("Result", model);
        }

        // GET: Sms/Balance
        public ActionResult Balance()
        {
            var client = new SmsClient();
            var model = client.QueryAccount();
            return View("Result", model);
        }

        // GET: Sms/Report
        public ActionResult Report()
        {
            var client = new SmsClient();
            var model = client.QueryReport();
            return View("Result", model);
        }

        // GET: Sms/UpdatePassword
        public ActionResult UpdatePassword()
        {
            return View("ResetPassword");
        }

        // POST: Sms/UpdatePassword
        [HttpPost]
        public ActionResult UpdatePassword(string password)
        {
            var client = new SmsClient();
            var model = client.UpdatePassword(password);
            return View("Result", model);
        }
    }
}

Zkly.Admin.Web/Views/Sms/Register.cshtml
<div class="row">
    <div class="col-sm-12">
        <div class="alert alert-success" role="alert">填写注册信息</div>
    </div>
    <div class="col-sm-10">

        @using (Html.BeginForm("Register", "Sms", FormMethod.Post, new { @class = "form-horizontal", role = "form", @id = "info-form" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                <label for="userName" class="col-xs-2 control-label">用户名<span class="text-danger">*</span></label>
                <div class="col-xs-10">
                    @Html.TextBox("userName", null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label for="mobile" class="col-xs-2 control-label">手机<span class="text-danger">*</span></label>
                <div class="col-xs-10">
                    @Html.TextBox("mobile", null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label for="phone" class="col-xs-2 control-label">办公室电话<span class="text-danger">*</span></label>
                <div class="col-xs-10">
                    @Html.TextBox("phone", null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label for="fax" class="col-xs-2 control-label">传真<span class="text-danger">*</span></label>
                <div class="col-xs-10">
                    @Html.TextBox("fax", null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label for="email" class="col-xs-2 control-label">电子邮箱<span class="text-danger">*</span></label>
                <div class="col-xs-10">
                    @Html.TextBox("email", null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label for="postcode" class="col-xs-2 control-label">邮编<span class="text-danger">*</span></label>
                <div class="col-xs-10">
                    @Html.TextBox("postcode", null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label for="company" class="col-xs-2 control-label">公司名<span class="text-danger">*</span></label>
                <div class="col-xs-10">
                    @Html.TextBox("company", null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label for="address" class="col-xs-2 control-label">公司地址<span class="text-danger">*</span></label>
                <div class="col-xs-10">
                    @Html.TextBox("address", null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-xs-2"></div>
                <div class="col-xs-10">
                    <a id="sms-register-btn" href="#" class="btn btn-primary btn-block">注 册</a>
                </div>
            </div>
        }
    </div>
</div>

Zkly.Admin.Web/Views/Sms/ResetPassword.cshtml
<div class="alert alert-danger" role="alert">当前模式下禁止修改短信服务密码!</div>

Zkly.Admin.Web/Views/Sms/Result.cshtml
@model Zkly.Common.SMS.SmsResult

@if (!Model.Success)
{
    <div class="alert alert-danger" role="alert">@Model.ErrorMessage</div>
}
<dl class="dl-horizontal dl-md">
    <dt>结果:</dt>
    <dd>
        @Model.Message
    </dd>
    <dt>Code:</dt>
    <dd>
        @Model.Code
    </dd>
    @if (!string.IsNullOrEmpty(Model.SmsId))
    {
        <dt>SMS-ID:</dt>
        <dd>
            @Model.SmsId
        </dd>
    }
    @if (!string.IsNullOrEmpty(Model.Balance))
    {
        <dt>剩余短信数:</dt>
        <dd>
            @Model.Balance
        </dd>
    }
    @if (!string.IsNullOrEmpty(Model.DailySubmited))
    {
        <dt>今日发送数:</dt>
        <dd>
            @Model.DailySubmited
        </dd>
    }
    @if (!string.IsNullOrEmpty(Model.SendingNumber))
    {
        <dt>正在发送数:</dt>
        <dd>
            @Model.SendingNumber
        </dd>
    }
    @if (!string.IsNullOrEmpty(Model.SuccessNumber))
    {
        <dt>成功发送数:</dt>
        <dd>
            @Model.SuccessNumber
        </dd>
    }
    @if (!string.IsNullOrEmpty(Model.WaitNumber))
    {
        <dt>等待发送数:</dt>
        <dd>
            @Model.WaitNumber
        </dd>
    }
    @if (!string.IsNullOrEmpty(Model.FailNumber))
    {
        <dt>失败发送数:</dt>
        <dd>
            @Model.FailNumber
        </dd>
    }
</dl>