Zkly.Web/Controllers/RoadshowController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Web.Caching;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;

using PagedList;

using Zkly.BLL.Message;
using Zkly.BLL.Repositories;
using Zkly.BLL.Vhall;
using Zkly.BLL.ViewModels;
using Zkly.Common;
using Zkly.Common.Extension;
using Zkly.Common.Log;
using Zkly.Common.Utils;
using Zkly.DAL.Models;

namespace Zkly.Web.Controllers
{
    public class RoadshowController : BaseController
    {
        #region lasy loading repository
        private const int PageSize = 12;
        private readonly IVhallApi vhallApi = new VhallApi();
        private RoadshowRepository roadshowRepository = new RoadshowRepository();
        private CapitalRoadshowRepository capitalRoadshowRepository = new CapitalRoadshowRepository();

        public RoadshowRepository RoadshowRepository
        {
            get { return this.roadshowRepository ?? (this.roadshowRepository = new RoadshowRepository()); }
        }

        public CapitalRoadshowRepository CapitalRoadshowRepository
        {
            get { return this.capitalRoadshowRepository ?? (this.capitalRoadshowRepository = new CapitalRoadshowRepository()); }
        }
        #endregion

        #region 路演厅

        #region 业务路演

        [Route("business-roadshow")]
        public ActionResult Business(int? page, string status)
        {
            status = status ?? "ongoing";
            ViewBag.Status = status;
            int pageNumber = page ?? 1;

            var roadshows = RoadshowRepository.GetRoadshowsByStatus(status);

            return View(roadshows.ToPagedList(pageNumber, PageSize));
        }

        [Route("business-roadshow/{id}")]
        public ActionResult BusinessRoadshow(int? id)
        {
            var model = RoadshowRepository.GetRoadshowById(id);

            return View("BusinessRoadshow", model);
        }

        //0:参与成功; 1:不是投资人; 2:参与失败;
        [HttpPost]
        public JsonResult Attend(Roadshow rd)
        {
            var userId = User.Identity.GetUserId();
            var isInvester = UserManager.IsInvestor(userId);
            var result = 0;

            try
            {
                if (!isInvester)
                {
                    result = 1;
                }
                else
                {
                    var invest = RoadshowRepository.GetInvestById(rd.Id);

                    if (invest != null && invest.Roadshow != null)
                    {
                        var body = new StringBuilder();
                        body.Append("投资人：").AppendLine(User.Identity.Name);
                        body.Append("邮箱：").AppendLine(UserManager.GetEmail(userId));
                        body.Append("联系电话：").AppendLine(UserManager.GetPhoneNumber(userId));
                        body.Append("感兴趣的公司：").AppendLine(invest.FirstAuditInfo.CompanyName);
                        body.Append("项目名：").AppendLine(invest.FirstAuditInfo.ProjectName);

                        var message = new IdentityMessage
                        {
                            Destination = ConfigurationManager.AppSettings["ZkjlEmail"],
                            Subject = "投资人申请参加资本路演",
                            Body = body.ToString()
                        };

                        var emailService = new EmailService();
                        emailService.Send(message);
                    }
                }
            }
            catch (Exception e)
            {
                Logger.Error(e.ToString());
                result = 2;
            }

            return new JsonResult { Data = result };
        }

        #endregion

        #region 资本路演

        public ActionResult Capital(int? page)
        {
            var capitals = CapitalRoadshowRepository.GetAllCapitalRoadshows();
            var pagingData = capitals.ToPagedList(page ?? 1, PageSize);

            foreach (var data in pagingData)
            {
                var status = this.vhallApi.GetActivityStatus(new ActivityStatus { WebinarId = data.WebinarId });
                data.Status = (EActivityStatus)Enum.Parse(typeof(EActivityStatus), status.Data);
            }

            return View(pagingData);
        }

        [Route("capital-roadshow/{id}")]
        public ActionResult CapitalRoadshow(int? id)
        {
            var model = CapitalRoadshowRepository.GetCapitalRoadshowById(id);
            var status = this.vhallApi.GetActivityStatus(new ActivityStatus { WebinarId = model.WebinarId });
            model.Status = EnumUtil.Parse<EActivityStatus>(status.Data);
            ViewBag.Email = UserManager.GetEmail(User.Identity.GetUserId());
            ViewBag.Name = User.Identity.Name;
            ViewBag.IsEnterprise = UserManager.IsEnterprise(User.Identity.GetUserId());

            return View("CapitalRoadshow", model);
        }

        public ActionResult LikeThisCapitalRoadshow(CapitalRoadshow capital)
        {
            var cr = CapitalRoadshowRepository.GetCapitalRoadshowById(capital.Id);

            if (cr != null)
            {
                var body = new StringBuilder();
                body.Append("投资人：").AppendLine(User.Identity.Name);
                body.Append("投资人Email：").AppendLine(UserManager.GetEmail(User.Identity.GetUserId()));
                body.Append("联系电话：").AppendLine(UserManager.GetPhoneNumber(User.Identity.GetUserId()));

                var msg = new IdentityMessage
                {
                    Destination = ConfigurationManager.AppSettings["ZkjlEmail"],
                    Subject = string.Format("投资人对公司：（{0}） 感兴趣", cr.CompanyName),
                    Body = body.ToString(),
                };

                UserManager.EmailService.Send(msg);
                return new JsonResult { Data = true };
            }

            return new JsonResult { Data = false };
        }
        #endregion

        #endregion

        #region 企业 - 业务路演的上传，修改

        /// <summary>
        /// 上传路演首页面，容许企业上传自己的也业务路演
        /// </summary>
        [Authorize]
        [Route("bussiness-roadshow/{id}")]
        public ActionResult RoadshowIndex(long id)
        {
            var invest = RoadshowRepository.GetInvestById(id);
            if (invest == null || invest.UserId != UserId)
            {
                ViewBag.Message = "无效的投资申请记录！";
                return View("Error");
            }

            var model = new RoadshowViewModel { Guid = Guid.NewGuid().ToString(), Id = id };
            if (invest.Roadshow != null)
            {
                model.VideoName = invest.Roadshow.VideoName;
                model.VideoDescrition = invest.Roadshow.VideoDescrition;
                model.CoverFileId = invest.Roadshow.CoverFileId;
                model.RoadshowAddress = invest.Roadshow.VhallRoadshowAddress;
            }

            return View("UploadIndex", model);
        }

        [HttpPost]
        public JsonResult Upload(RoadshowViewModel model)
        {
            var message = string.Empty;
            var result = false;

            try
            {
                var getError = CheckUploadData(model);
                if (getError.Count>0)
                {
                    return new JsonResult { Data = new { status = result, message = getError.Join(",") } };
                }
                else
                {
                    var temproadshow = new RoadshowRepository().GetRoadshowById(model.Id);

                    RoadshowRepository.UploadInfo = this.SetUploadToCache;
                    if (temproadshow == null)
                    {
                        result = RoadshowRepository.AddRoadshow(model);
                    }
                    else
                    {
                        result = RoadshowRepository.EditRoadshow(model);
                    }

                    return new JsonResult { Data = new { status = result, message ="数据保存成功！" } };
                }
            }
            catch (Exception ex)
            {
                Logger.Error(ex.ToString());
                message = ex.ToString();
            }

            return new JsonResult { Data = new { status = false, message = message } };
        }

        public IList<string> CheckUploadData(RoadshowViewModel model)
        {
            List<string> list=new List<string>();
            var contentLength = Convert.ToDouble(model.VideoFile.ContentLength);
            var limitedUploadCapacity = 500;
         
            if (model.VideoFile==null)
            {
                list.Add("上传视频文件不能为空!");
            }
            else
            {
                if (!FileHelper.VideoContentTypeList().Contains(model.VideoFile.ContentType.ToLower()))
                {
                    list.Add("上传视频文件格式不正确!");
                }
            }

            if (string.IsNullOrEmpty(model.VideoName))
            {
                list.Add("视频名称不能为空!");
            }

            if (string.IsNullOrEmpty(model.VideoDescrition))
            {
                list.Add("视频简介不能为空!");
            }

            if (model.CoverFile==null)
            {
                list.Add("活动封面不能为空!");
            }

            if (contentLength / 1024d / 1024d > limitedUploadCapacity)
            {
                 list.Add("视频文件大于500M!"); 
            }

            return list;
        }

        [ActionName("upload-success")]
        public ActionResult UploadSuccess()
        {
            ViewBag.Message = "完成，路演已成功提交。";
            return View("Success_Info", new ResultViewModel { ActionName = "index", ControllerName = "enterprise" });
        }

        public void SetUploadToCache(string text, long valueNow, long valueMax, string guid)
        {
            var cachedItem = HttpContext.Cache[guid];
            if (cachedItem != null)
            {
                HttpContext.Cache.Remove(guid);
            }

            HttpContext.Cache.Add(

Zkly.Web/Views/Roadshow/Business.cshtml
@model PagedList.IPagedList<Zkly.DAL.Models.Roadshow>
@using PagedList.Mvc;

@{
    ViewBag.Title = "业务路演大厅";
}
@section heads{
    @Styles.Render("~/css/roadshow-item")
    @Styles.Render("~/css/business")
    @Styles.Render("~/css/PagedList")
}
<div class="business-hall">
    <ol class="breadcrumb">
        <li><a href="/">首页</a></li>
        <li><a href="@Url.Action("Business", "Roadshow")">路演厅</a></li>
        <li class="active">业务路演</li>
    </ol>

    <div>
        <div class="title">
            <i></i>
            <p>业务路演</p>

            @Html.ActionLink("路演中", "business", "roadshow", new { status = "ongoing" }, new { @class = ViewBag.Status == "ongoing" ? "on" : "" })
            @Html.ActionLink("已结束", "business", "roadshow", new { status = "done" }, new { @class = ViewBag.Status == "done" ? "on" : "" })
        </div>      
        
        <div class="roadshow">
            @if (Model.Count == 0 || (Model.Count == 1 && Model[0] == null))
            {
                <div class="no-data-tip">目前还没有业务路演！</div>
            }
            else
            {
                <div class="items">
                    <ul>
                        @foreach (var item in Model)
                        {
                            if (item != null)
                            {
                                <li>
                                    @Html.Partial("Template/RoadshowItem", item)
                                </li>
                            }
                        }
                    </ul>

                    <div class="clearfix"></div>
                </div>
                <div>
                    @Html.PagedListPager(Model, page => Url.Action("business", "roadshow", new { page, status = ViewBag.Status }), new PagedListRenderOptions() { LinkToFirstPageFormat = "首页", LinkToNextPageFormat = "下一页", LinkToPreviousPageFormat = "上一页", LinkToLastPageFormat = "末页", DisplayItemSliceAndTotal = false, MaximumPageNumbersToDisplay = 8 })
                </div>
            }
        </div>
    </div>
</div>

Zkly.Web/Views/Roadshow/BusinessRoadshow.cshtml
@model Zkly.DAL.Models.Roadshow
@{
    ViewBag.Title = "观看业务路演";
}
<br />
<div class="row">
    @Html.Partial("AlertMessage")
</div>
<div class="row">
    <div class="col-xs-12">
        @if (string.IsNullOrEmpty(Model.VhallRoadshowAddress))
        {
            <div class="jumbotron">
                <h1>视频暂时无法播放</h1>
                <p>服务器正在对该视频文件进行编码处理，请稍候再试。如果该视频长时间依然无法访问，请联系客服人员处理。</p>
                <p><a class="btn btn-primary btn-lg" href="@Url.Action("Business", "Roadshow")" role="button">返回</a></p>
            </div>
        }
        else
        {
            <iframe border="0" src="@Model.VhallRoadshowAddress" width="1062" height="600"></iframe>
            @*<embed class="zkly-biz-embed" src="@Model.VhallRoadshowAddress" autostart="true" loop="true">*@
        }
    </div>
</div>

<div class="row zkly-biz-container">
    <div class="col-xs-12 zkly-biz-title">
        @Model.VideoName
    </div>
    <div class="col-xs-12 zkly-biz-desc">
        @Model.VideoDescrition
    </div>
    <div class="col-xs-12">
        <a id="attend" class="btn btn-primary" data-roadshow-id="@Model.Id" href="javascript:void(0);">我要参加资本路演</a>
    </div>
</div>


@section scripts {
   @Scripts.Render("~/js/business-roadshow-manager")

}

Zkly.Web/Views/Roadshow/Capital.cshtml
@model PagedList.IPagedList<Zkly.DAL.Models.CapitalRoadshow>
@using PagedList.Mvc;

@{
    ViewBag.Title = "资本路演大厅";
}
@section heads{
    @Styles.Render("~/css/PagedList")
    @Styles.Render("~/css/roadshow-item")
    @Styles.Render("~/css/business")
}

<div class="business-hall">
    <ol class="breadcrumb">
        <li><a href="/">首页</a></li>
        <li><a href="@Url.Action("Capital", "Roadshow")">路演厅</a></li>
        <li class="active">资本路演</li>
    </ol>

    <div>
        <div class="title">
            <i></i>
            <p>资本路演</p>

            @*@Html.ActionLink("路演中", "business", "roadshow", new { status = "ongoing" }, new { @class = ViewBag.Status == "ongoing" ? "on" : "" })
            @Html.ActionLink("已结束", "business", "roadshow", new { status = "done" }, new { @class = ViewBag.Status == "done" ? "on" : "" })*@
        </div>

        <div class="roadshow">
            @if (Model.Count == 0 || (Model.Count == 1 && Model[0] == null))
            {
                <div class="no-data-tip">目前还没有资本路演！</div>
            }
            else
            {
                <div class="items">
                    <ul>
                        @foreach (var item in Model)
                        {
                            if (item != null)
                            {
                                <li>
                                    @Html.Partial("Template/CapitalRoadshowItem", item)
                                </li>
                            }
                        }
                    </ul>

                    <div class="clearfix"></div>
                </div>
                <div>
                    @Html.PagedListPager(Model, page => Url.Action("capital", "roadshow"), new PagedListRenderOptions() { LinkToFirstPageFormat = "首页", LinkToNextPageFormat = "下一页", LinkToPreviousPageFormat = "上一页", LinkToLastPageFormat = "末页", DisplayItemSliceAndTotal = false, MaximumPageNumbersToDisplay = 8 })
                </div>
            }
        </div>
    </div>
</div>

Zkly.Web/Views/Roadshow/CapitalRoadshow.cshtml
@model Zkly.DAL.Models.CapitalRoadshow
@using Zkly.Common.Config;
@using Zkly.BLL.Vhall;
@{
    ViewBag.Title = "观看资本路演";
}
<br />
<div class="row">
    @Html.Partial("AlertMessage")
</div>

<div class="row">
    <div class="col-xs-12">
        @if (Model.Status == EActivityStatus.End)
        {
            <span>直播已结束，请观看录播</span>
            <iframe class="zkly-capital-container" src="@VhallUtil.GetRecordUrl(Model.WebinarId)"></iframe>
        }
        else
        {
            var url = ViewBag.IsEnterprise != null && ViewBag.IsEnterprise ? VhallSettings.WebinarGuestUrl : VhallSettings.WebinarUrl;
            
            <iframe class="zkly-capital-container" src="@string.Format(url, Model.WebinarId, ViewBag.Email, ViewBag.Name)"></iframe>
        }
    </div>
</div>
<div class="row">
    <div class="col-xs-10">
        <div class="zkly-capital-subject">@Model.Subject</div>
        <div>直播时间：@Model.StartDate - @Model.EndDate</div>
    </div>
    <div class="col-xs-2">
        <a id="like-this-capital" href="#" data-id="@Model.Id" class="btn btn-primary">我对该企业感兴趣</a>
    </div>
</div>
<div class="row zkly-capital-desc">@Model.Description</div>


@section scripts{

@Scripts.Render("~/js/capital-roadshow-manager")
}

Zkly.Web/Views/Roadshow/Hall.cshtml
@model Zkly.BLL.ViewModels.RoadshowHallViewModel

@{
    ViewBag.Title = "路演厅";
}
<br />
<div class="panel panel-default">
    <div class="panel-heading">
        <span>业务路演</span>
        @if (Model.BusinessRoadshows != null && Model.BusinessRoadshows.Count() > 0)
        {
            <a href="#" class="zkly-right">更多...</a>
        }
    </div>
    <div class="panel-body">
        @if (Model.BusinessRoadshows == null || Model.BusinessRoadshows.Count() == 0)
        {
            <p>目前还没有业务路演可以观看！</p>
        }
        else
        {
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>视频名称</th>
                        <th>视频描述</th>
                        <th>提交时间</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.BusinessRoadshows)
                    {
                        <tr>
                            <td>@item.VideoName</td>
                            <td class="zkly-my-roadshow-desc">@item.VideoDescrition</td>
                            <td>@item.SubmitDate</td>
                            <td><a href="roadshow/business-roadshow/@item.Id" class="btn btn-info">进入</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <span>资本路演</span>
        @if (Model.CapitalRoadshows != null && Model.CapitalRoadshows.Count() > 0)
        {
            <a href="#" class="zkly-right">查看更多...</a>
        }
    </div>
    <div class="panel-body">
        @if (Model.CapitalRoadshows == null || Model.CapitalRoadshows.Count() == 0)
        {
            <p>目前还没有资本路演可以观看！</p>
        }
        else
        {
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>公司名称</th>
                        <th>活动主题</th>
                        <th>开始时间</th>
                        <th>结束时间</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.CapitalRoadshows)
                    {
                        <tr>
                            <td>@item.CompanyName</td>
                            <td>@item.Subject</td>
                            <td>@item.StartDate.ToString("yyyy-MM-dd hh:mm")</td>
                            <td>@item.EndDate.ToString("yyyy-MM-dd hh:mm")</td>                           
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

Zkly.Web/Views/Roadshow/UploadIndex.cshtml
@model Zkly.BLL.ViewModels.RoadshowViewModel
@{
    ViewBag.Title = "业务路演上传";
}

@section heads{

    @Styles.Render("~/css/invest")
    @Styles.Render("~/css/fileinput")
    @Styles.Render("~/css/ProgressBar")
    @Styles.Render("~/css/business")
    @Styles.Render("~/css/bootstrapValidatorCss")


    @Scripts.Render("~/js/jquery-form")
    @Scripts.Render("~/js/fileinput")
    @Scripts.Render("~/js/bootstrapValidator")
}

<div class="invest">
    @Html.Partial("_InvestTop", EInvestAuditStage.Roadshow)

    <div class="content panel panel-default">

        <div class="container ">
            <br />
            @Html.Partial("AlertMessage")
            @using (Html.BeginForm("upload", "roadshow", FormMethod.Post, new { @class = "form-horizontal", id = "upload-form", role = "form", enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(m => m.Id, new { id = "roadshow-id" })
                @Html.HiddenFor(m => m.Guid)
                <div class="row zkly-upload-item">
                    <div class="col-md-3 control-label">
                        <label>路演视频 </label>
                        <span class="validation-fail">*</span>
                    </div>
                    <div class="col-md-9">

                        @{
                            <!--已经提交了表单-->
                            bool isSubmitedForm = !string.IsNullOrEmpty(Model.VideoName);

                            string cssStr = isSubmitedForm ? "display:none" : "display:block";

                        }


                        <div id="showUploadVideo" style="@cssStr">
                            <div class="zkly-upload-video">
                                <input type="file" id="videoFile" accept="video/*" name="VideoFile" value="" class="zkly-input-file" />
                            </div>
                            <span class="zkly-upload-tip">大小：不能超过500M，格式：rm,rmvb,wmv,avi,mpg,mpeg,mp4</span>
                            <div id="showVideo"></div>
                        </div>


                      
                        @if (isSubmitedForm)
                        {
                            <br />
                            <div id="playRoadshowVideo">
                                    @if (!string.IsNullOrEmpty(Model.RoadshowAddress))
                                    {
                                      <iframe border="0" src="@Model.RoadshowAddress" width="800" height="600"></iframe>
                                    }
                                    else
                                    {
                                        <div class="jumbotron">
                                            <h1>视频暂时无法播放</h1>
                                            <p>服务器正在对该视频文件进行编码处理，请稍候再试。如果该视频长时间依然无法访问，请联系客服人员处理。</p>
                                            <p><a class="btn btn-primary btn-lg" href="@Url.Action("Index", "Enterprise")" role="button">返回</a></p>
                                        </div>
                                    }
                            </div>
                            <button class="btn btn-primary" id="updateRoadshowVideo">修改</button>
                        }


                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3 control-label">
                        <label>视频名称 </label><span class="validation-fail">*</span>
                    </div>
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.VideoName, new { @class = "form-control zkly-upload-video-name", id = "vedioName", placeholder = "视频名称" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3 control-label">
                        <label>视频简介 </label><span class="validation-fail">*</span>
                    </div>
                    <div class="col-md-9" id="myVideoDescrition">
                        @Html.TextAreaFor(m => m.VideoDescrition, new { @class = "form-control zkly-upload-video-desc", id = "videoDescription", placeholder = "视频简介" })
                    </div>
                </div>


                <div class="row zkly-upload-item">
                    <div class="col-md-3 control-label">
                        <label>活动封面 </label>
                        <span class="validation-fail">*</span>
                    </div>
                    <div class="col-md-9">
                        @if (Model.CoverFileId > 0)
                        {
                            <div class="RoadshowCover">
                                <img class="thumbnail" src='@Url.Action("FileDisplayById", "File", new { id = Model.CoverFileId })' alt='活动封面' />
                            </div>
                        }
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <div class="fileinput-preview thumbnail" data-trigger="fileinput" name="i" id="businessLicense"></div>
                            <div>
                                <span class="btn btn-default btn-file">
                                    <span class="fileinput-new">选择图片</span><span class="fileinput-exists">改变</span>
                                    <input type="file" id="coverFile" accept="image/jpg,png" name="CoverFile" value="" class="zkly-input-file" />
                                </span>
                                <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">移除</a>
                                &nbsp;&nbsp;<span class="text-danger" id="businessLicenseError">格式错误</span>
                            </div>
                        </div>
                        <span class="zkly-upload-tip">大小：不能超过2M，格式：jpg,png</span>
                        <div id="showCover"></div>

                    </div>
                </div>



                <div class="row zkly-upload-item">
                    <div class="col-md-3">

                    </div>
                    <div class="col-md-9">
                        <input id="protocol" type="checkbox" />我已阅读并同意签署《<a href="">XXX协议</a>》
                    </div>
                </div>




                <div class="col-md-12 zkly-progress-bar hidden">
                    <div class="progress">
                        <div class="bar"></div>
                        <div class="percent">0%</div>
                    </div>

                    <div id="status"></div>

                    <div class="zkly-progress-info">
                        <div class="current-text pull-left" id="progressBarWords">文件比较大，请耐心等候</div>
                        <div class="pull-left">
                            <img id="loading" src="~/Images/PublicImg/loading-small.gif" />
                        </div>
                    </div>
                </div>



                <div class="row zkly-upload-item">
                    <div class="col-md-3">
                    </div>
                    <div class="col-md-9">
                        <button type="button" id="uploadBtn" class="btn btn-primary disabled">上传路演</button>
                        @Html.ActionLink("返回", "index", "enterprise", null, new { @class = "btn btn-default" })
                    </div>
                </div>

            }
        </div>
    </div>
</div>

@section scripts{

    @Scripts.Render("~/js/upload")
    @Scripts.Render("~/js/enterprise-invest")
}